Marathonrunners/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.WebPages;
using Marathonrunners.Core;
using Marathonrunners.Models;

namespace Marathonrunners.Controllers {
    public class SettingController : Controller {
        //
        // GET: /Setting/
        private IAccountRepository _accountRepository;
        public SettingController(IAccountRepository accountRepository) {
            _accountRepository = accountRepository;
        }

        [HttpPost]
        [AllowAnonymous]
        public PartialViewResult Gender() {
            return PartialView("Gender");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult GenderUpdate(UpdateViewModelGender gendermodel) {
            // TODO: hardcoded here find a better way.
            var title = new string[] { "Male", "Female" };
            if (ModelState.IsValid) {
                // TODO: Make a JSON object instead?
                ViewBag.Value = string.Format("\'{{\"field\":\"{0}\",\"value\":\"{1}\"}}\'", "title", title[gendermodel.Title - 1]);
                _accountRepository.UpdateField("Gender", gendermodel.Title.ToString(), User.Identity.Name, 1);
                return PartialView("Success");
            }
            return PartialView("Gender", gendermodel);
        }

        [HttpPost]
        [AllowAnonymous]
        public PartialViewResult FirstName() {
            return PartialView("FirstName");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult FirstNameUpdate(UpdateViewModelFirstName firstNameModel) {
            if (ModelState.IsValid) {
                // TODO: Make a JSON object instead?
                ViewBag.Value = string.Format("\'{{\"field\":\"{0}\",\"value\":\"{1}\"}}\'", "firstname_view", firstNameModel.FirstName);
                _accountRepository.UpdateField("FirstName", firstNameModel.FirstName, User.Identity.Name, 3);
                return PartialView("Success");
            }
            return PartialView("FirstName", firstNameModel);
        }

        [HttpPost]
        [AllowAnonymous]
        public PartialViewResult LastName() {
            return PartialView("LastName");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult LastNameUpdate(UpdateViewModelLastName lastNameModel) {
            if (ModelState.IsValid) {
                // TODO: Make a JSON object instead?
                ViewBag.Value = string.Format("\'{{\"field\":\"{0}\",\"value\":\"{1}\"}}\'", "lastname_view", lastNameModel.LastName);
                _accountRepository.UpdateField("LastName", lastNameModel.LastName, User.Identity.Name, 3);
                return PartialView("Success");
            }
            return PartialView("LastName", lastNameModel);
        }

        [HttpPost]
        [AllowAnonymous]
        public PartialViewResult DateOfBirth() {
            return PartialView("DateOfBirth");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult DateOfBirthUpdate(UpdateViewModelDateOfBirth dateOfBirthModel) {
            if (ModelState.IsValid) {
                // TODO: Make a JSON object instead?
                ViewBag.Value = string.Format("\'{{\"field\":\"{0}\",\"value\":\"{1}\"}}\'", "dob_view", dateOfBirthModel.DateOfBirth.Date.ToString("yyyy-MM-dd"));
                _accountRepository.UpdateField("DOB", dateOfBirthModel.DateOfBirth.Date.ToString("yyyy-MM-dd"), User.Identity.Name, 3);
                return PartialView("Success");
            }
            return PartialView("DateOfBirth", dateOfBirthModel);
        }

        [HttpPost]
        [AllowAnonymous]
        public PartialViewResult Nationality() {
            return PartialView("Nationality");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult NationalityUpdate(UpdateViewModelNationality nationalityModel) {
            if (ModelState.IsValid) {
                // TODO: Make a JSON object instead?
                ViewBag.Value = string.Format("\'{{\"field\":\"{0}\",\"value\":\"{1}\"}}\'", "nationality_view", nationalityModel.Nationality);
                _accountRepository.UpdateField("Nationaility", nationalityModel.Nationality, User.Identity.Name, 3);
                return PartialView("Success");
            }
            return PartialView("Nationality", nationalityModel);
        }

        [HttpPost]
        [AllowAnonymous]
        public PartialViewResult UserLocation() {
            return PartialView("UserLocation");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult UserLocationUpdate(UpdateViewModelUserLocation userLocationModel) {
            try {
                if (userLocationModel.Country != "India") {
                    bool error = false;
                    if (string.IsNullOrEmpty(userLocationModel.OtherCity)) {
                        error = true;
                        ModelState.AddModelError("OtherCity", "Other City cannot be empty");
                    }
                    if (string.IsNullOrEmpty(userLocationModel.OtherState)) {
                        error = true;
                        ModelState.AddModelError("OtherState", "Other State cannot be empty");
                    }
                    if (error) return PartialView("UserLocation", userLocationModel);
                }
                if (userLocationModel.Country != "India" || ModelState.IsValid) {
                    // TODO: Make a JSON object instead?
                    ViewBag.Location = true;
                    ViewBag.Value = "\'[" +
                                    string.Format("{{\"field\":\"{0}\",\"value\":\"{1}\"}},", "country_view",
                                        userLocationModel.Country) +
                                    string.Format("{{\"field\":\"{0}\",\"value\":\"{1}\"}},", "state_view",
                                        userLocationModel.State) +
                                    string.Format("{{\"field\":\"{0}\",\"value\":\"{1}\"}},", "city_view",
                                        userLocationModel.City) +
                                    string.Format("{{\"field\":\"{0}\",\"value\":\"{1}\"}},", "otherstate_view",
                                        userLocationModel.OtherState) +
                                    string.Format("{{\"field\":\"{0}\",\"value\":\"{1}\"}}", "othercity_view",
                                        userLocationModel.OtherCity) +
                                    "]\'";
                    var values = new List<string>(){
                        userLocationModel.Country,
                        userLocationModel.Country != "India" ? userLocationModel.OtherState: 
                        userLocationModel.State ?? userLocationModel.OtherState,
                        userLocationModel.Country != "India" ? userLocationModel.OtherCity : userLocationModel.City ?? userLocationModel.OtherCity,
                    };
                    _accountRepository.UpdateUserLocation(values, userLocationModel.PostalCode, User.Identity.Name);
                    return PartialView("Success");
                }
            } catch (Exception ex) {
                ModelState.AddModelError("", ex.Message);
            }
            return PartialView("UserLocation", userLocationModel);
        }

        [HttpPost]
        [AllowAnonymous]
        public PartialViewResult Address() {
            return PartialView("Address");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult AddressUpdate(UpdateViewModelAddress addressModel) {
            if (ModelState.IsValid) {
                // TODO: Make a JSON object instead?
                ViewBag.Value = string.Format("\'{{\"field\":\"{0}\",\"value\":\"{1}\"}}\'", "address_view", addressModel.Address);
                _accountRepository.UpdateField("Address", Server.HtmlEncode(addressModel.Address), User.Identity.Name, 3);
                return PartialView("Success");
            }
            return PartialView("Address", addressModel);
        }

        [HttpPost]
        [AllowAnonymous]
        public PartialViewResult Mobile() {
            return PartialView("Mobile");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult MobileUpdate(UpdateViewModelMobile mobileModel) {
            if (ModelState.IsValid) {
                // TODO: Make a JSON object instead?
                ViewBag.Value = string.Format("\'{{\"field\":\"{0}\",\"value\":\"{1}\"}}\'", "mobile_view", mobileModel.MobileNum);
                _accountRepository.UpdateField("MobileNumber", mobileModel.MobileNum.ToString(), User.Identity.Name, 1);
                return PartialView("Success");
            }
            return PartialView("Mobile", mobileModel);
        }


        [HttpPost]
        [AllowAnonymous]
        public PartialViewResult Occupation() {
            return PartialView("Occupation");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult OccupationUpdate(UpdateViewModelOccupation occupationModel) {
            if (ModelState.IsValid) {
                // TODO: Make a JSON object instead?
                ViewBag.Value = string.Format("\'{{\"field\":\"{0}\",\"value\":\"{1}\"}}\'", "occupation_view", occupationModel.Occupation);
                _accountRepository.UpdateField("Occupation", occupationModel.Occupation, User.Identity.Name, 3);
                return PartialView("Success");
            }
            return PartialView("Occupation", occupationModel);

Marathonrunners/Views/Setting/Address.cshtml
@model Marathonrunners.Models.UpdateViewModelAddress
<div id="addressupdate">
    @using (Ajax.BeginForm("AddressUpdate", "Setting", new AjaxOptions {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "addressupdate",
        OnFailure = "update_ended",
        //OnSuccess = ""
    })) {
        @Html.AntiForgeryToken()
        <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.Address)</span>
        <div class="clk2raceSettingsListContent">
            @Html.TextAreaFor(model => model.Address, new { @name = "address", @id = "address", @placeholder = "Address", @maxlength = "200", @cols = "26", @rows = "3" })
            @Html.ValidationMessageFor(model => model.Address)
        </div>
        <span class="clk2raceSettingsListGroupEdit">
            <input class="buttonlink" type="submit" value="Update" />
            <a class="buttonlink" onclick="toggle_field_section(this)"><i class="fa fa-times fa-lg"></i></a>
        </span>
    }
</div>

Marathonrunners/Views/Setting/ChronicDisease.cshtml
@model Marathonrunners.Models.UpdateViewModelChronicDisease
    <div id="firstnameupdate">
        @using (Ajax.BeginForm("ChronicDiseaseUpdate", "Setting", new AjaxOptions {
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "firstnameupdate",
            OnFailure = "update_ended"
        })) {
            @Html.AntiForgeryToken()
            <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.ChronicDisease)</span>
            <div class="clk2raceSettingsListContent">
                @Html.TextBoxFor(model => model.ChronicDisease, new {
           @class = "chars", @name = "chronicdisease", @id = "chronicdisease",
           @placeholder = "None", @autocomplete = "off", @maxlength = "20"
       })
                @Html.ValidationMessageFor(model => model.ChronicDisease)
            </div>
            <span class="clk2raceSettingsListGroupEdit">
                <input class="buttonlink" type="submit" value="Update" />
                <a class="buttonlink" onclick="toggle_field_section(this)"><i class="fa fa-times fa-lg"></i></a>
            </span>
        }
    </div>

Marathonrunners/Views/Setting/DateOfBirth.cshtml
@model Marathonrunners.Models.UpdateViewModelDateOfBirth
<div id="dobupdate">
    @using (Ajax.BeginForm("DateOfBirthUpdate", "Setting", new AjaxOptions {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "dobupdate",
        OnFailure = "update_ended",
        OnSuccess = "load_datepicker"
    })) {
        @Html.AntiForgeryToken()
        <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.DateOfBirth)</span>
        <div class="clk2raceSettingsListContent">
            @Html.TextBoxFor(model => model.DateOfBirth, new { @name = "datebirth", @id = "datebirth", @placeholder = "yyyy-mm-dd", @readonly = "readonly"})
            @Html.ValidationMessageFor(model => model.DateOfBirth)
        </div>
        <span class="clk2raceSettingsListGroupEdit">
            <input class="buttonlink" type="submit" value="Update" />
            <a class="buttonlink" onclick="toggle_field_section(this)"><i class="fa fa-times fa-lg"></i></a>
        </span>
    }
</div>

Marathonrunners/Views/Setting/EmergencyContactName.cshtml
@model Marathonrunners.Models.UpdateViewModelEmergencyContactName
<div id="emergencycontactnameupdate">
    @using (Ajax.BeginForm("EmergencyContactNameUpdate", "Setting", new AjaxOptions {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "emergencycontactnameupdate",
        OnFailure = "update_ended",
        //OnSuccess = ""
    })) {
        @Html.AntiForgeryToken()
        <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.EmergencyContactName)</span>
        <div class="clk2raceSettingsListContent">
            @Html.TextBoxFor(model => model.EmergencyContactName, new { @name = "emcontactname", @id = "emcontactname", @placeholder = "Emergency Contact Name" })
            @Html.ValidationMessageFor(model => model.EmergencyContactName)
        </div>
        <span class="clk2raceSettingsListGroupEdit">
            <input class="buttonlink" type="submit" value="Update" />
            <a class="buttonlink" onclick="toggle_field_section(this)"><i class="fa fa-times fa-lg"></i></a>
        </span>
    }
</div>

Marathonrunners/Views/Setting/FirstName.cshtml
@model Marathonrunners.Models.UpdateViewModelFirstName
<div id="firstnameupdate">
    @using (Ajax.BeginForm("FirstNameUpdate", "Setting", new AjaxOptions {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "firstnameupdate",
        OnFailure = "update_ended"
    })) {
        @Html.AntiForgeryToken()
        <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.FirstName)</span>
        <div class="clk2raceSettingsListContent">
            @Html.TextBoxFor(model => model.FirstName, new {
           @class = "chars", @name = "inputFname", @id = "inputFname",
           @placeholder = "First Name", @autocomplete = "off"})
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>
        <span class="clk2raceSettingsListGroupEdit">
            <input class="buttonlink" type="submit" value="Update" />
            <a class="buttonlink" onclick="toggle_field_section(this)"><i class="fa fa-times fa-lg"></i></a>
        </span>
    }
</div>

Marathonrunners/Views/Setting/Gender.cshtml
@model Marathonrunners.Models.UpdateViewModelGender
<div id="titleupdate">
    @using (Ajax.BeginForm("GenderUpdate", "Setting", new AjaxOptions {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "titleupdate",
        OnFailure = "update_ended"
    })) {
        @Html.AntiForgeryToken()
        <span class="clk2raceSettingsListLabel">Select Gender</span>
        <div class="clk2raceSettingsListContent">
            @Html.DropDownListFor(model => model.Title,
            new List<SelectListItem>{
                new SelectListItem { Text = "-", Value = ""},
                new SelectListItem { Text = "Male", Value = "1"},
                new SelectListItem { Text = "Female", Value = "2"}
                 
            }, new { @id = "title", @name = "Gender" })
            @Html.ValidationMessageFor(model => model.Title)
        </div>
        <span class="clk2raceSettingsListGroupEdit">
            <input class="buttonlink" type="submit" value="Update" />
            <a class="buttonlink" onclick="toggle_field_section(this)"><i class="fa fa-times fa-lg"></i></a>
        </span>
    }
</div>

Marathonrunners/Views/Setting/IdNum.cshtml
@model Marathonrunners.Models.UpdateViewModelIDNum
<div id="idnumupdate">
    @using (Ajax.BeginForm("IdNumUpdate", "Setting", new AjaxOptions {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "idnumupdate",
        OnFailure = "update_ended",
        //OnSuccess = ""
    })) {
        @Html.AntiForgeryToken()
        <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.IDNum)</span>
        <div class="clk2raceSettingsListContent">
            @Html.TextBoxFor(model => model.IDNum, new { @name = "idno", @id = "idno", @placeholder = "ID Number", @maxlength = "20" })
            @Html.ValidationMessageFor(model => model.IDNum)
        </div>
        <span class="clk2raceSettingsListGroupEdit">
            <input class="buttonlink" type="submit" value="Update" />
            <a class="buttonlink" onclick="toggle_field_section(this)"><i class="fa fa-times fa-lg"></i></a>
        </span>
    }
</div>

Marathonrunners/Views/Setting/LastName.cshtml
@model Marathonrunners.Models.UpdateViewModelLastName
<div id="lastnameupdate">
    @using (Ajax.BeginForm("LastNameUpdate", "Setting", new AjaxOptions {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "lastnameupdate",
        OnFailure = "update_ended"
    })) {
        @Html.AntiForgeryToken()
        <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.LastName)</span>
        <div class="clk2raceSettingsListContent">
            @Html.TextBoxFor(model => model.LastName, new { @class = "chars", @name = "inputLnam", @id = "inputLnam", @placeholder = "Last Name", @autocomplete = "off" })
            @Html.ValidationMessageFor(model => model.LastName)
        </div>
        <span class="clk2raceSettingsListGroupEdit">
            <input class="buttonlink" type="submit" value="Update" />
            <a class="buttonlink" onclick="toggle_field_section(this)"><i class="fa fa-times fa-lg"></i></a>
        </span>
    }
</div>

Marathonrunners/Views/Setting/Mobile.cshtml
@model Marathonrunners.Models.UpdateViewModelMobile
<div id="mobileupdate">
    @using (Ajax.BeginForm("MobileUpdate", "Setting", new AjaxOptions {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "mobileupdate",
        OnFailure = "update_ended",
        //OnSuccess = ""
    })) {
        @Html.AntiForgeryToken()
        <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.MobileNum)</span>
        <div class="clk2raceSettingsListContent">
            @Html.TextBoxFor(model => model.MobileNum, new { @class = "nums", @name = "mobile", @id = "mobile", @placeholder = "Mobile Number with country code",@minlength = "10",@maxlength = "15" })
            @Html.ValidationMessageFor(model => model.MobileNum)
        </div>
        <span class="clk2raceSettingsListGroupEdit">
            <input class="buttonlink" type="submit" value="Update" />
            <a class="buttonlink" onclick="toggle_field_section(this)"><i class="fa fa-times fa-lg"></i></a>
        </span>
    }
</div>

Marathonrunners/Views/Setting/NameOnBib.cshtml
@model Marathonrunners.Models.UpdateViewModelNameOnBIB
<div id="firstnameupdate">
    @using (Ajax.BeginForm("NameOnBibUpdate", "Setting", new AjaxOptions {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "firstnameupdate",
        OnFailure = "update_ended"
    })) {
        @Html.AntiForgeryToken()
        <span class="clk2raceSettingsListLabel">
            @Html.LabelFor(model => model.NameOnBIB
        )
        </span>
        <div class="clk2raceSettingsListContent">
            @Html.TextBoxFor(model => model.NameOnBIB, new {
           @class = "chars", @name = "nameonbib", @id = "nameonbib",
           @placeholder = "Name on BIB", @autocomplete = "off", @maxlength = "8"
       })
            @Html.ValidationMessageFor(model => model.NameOnBIB)
        </div>
        <span class="clk2raceSettingsListGroupEdit">
            <input class="buttonlink" type="submit" value="Update" />
            <a class="buttonlink" onclick="toggle_field_section(this)"><i class="fa fa-times fa-lg"></i></a>
        </span>
    }
</div>

Marathonrunners/Views/Setting/RunningClub.cshtml
@model Marathonrunners.Models.UpdateViewModelRunningClub
<div id="runningclubupdate">
    @using (Ajax.BeginForm("RunningClubUpdate", "Setting", new AjaxOptions {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "runningclubupdate",
        OnFailure = "update_ended",
        //OnSuccess = ""
    })) {
        @Html.AntiForgeryToken()
        <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.RunningClub)</span>
        <div class="clk2raceSettingsListContent">
            @Html.TextBoxFor(model => model.RunningClub, new { @name = "runclub", @id = "runclub", @placeholder = "None", @value = "None" })
            @Html.ValidationMessageFor(model => model.RunningClub)
        </div>
        <span class="clk2raceSettingsListGroupEdit">
            <input class="buttonlink" type="submit" value="Update" />
            <a class="buttonlink" onclick="toggle_field_section(this)"><i class="fa fa-times fa-lg"></i></a>
        </span>
    }
</div>

Marathonrunners/Views/Setting/ShirtSize.cshtml
@model Marathonrunners.Models.UpdateViewModelShirtSize
<div id="shirtsizeupdate">
    @using (Ajax.BeginForm("ShirtSizeUpdate", "Setting", new AjaxOptions {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "shirtsizeupdate",
        OnFailure = "update_ended",
        //OnSuccess = ""
    })) {
        @Html.AntiForgeryToken()
        <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.ShirtSize)</span>
        <div class="clk2raceSettingsListContent">
            @Html.DropDownListFor(model => model.ShirtSize,
                                        new List<SelectListItem>{
                                            new SelectListItem { Text = "Select Size", Value = ""},
                                            //new SelectListItem { Text = "XL", Value = "XXL"},
                                            new SelectListItem { Text = "XL", Value = "XL"},
                                            new SelectListItem { Text = "L", Value = "L"},
                                            new SelectListItem { Text = "M", Value = "M"},
                                            new SelectListItem { Text = "S", Value = "S"},
                                        }, new { @id = "tshirt_size", @name = "tshirt_size" })
            @Html.ValidationMessageFor(model => model.ShirtSize)
        </div>
        <span class="clk2raceSettingsListGroupEdit">
            <input class="buttonlink" type="submit" value="Update" />
            <a class="buttonlink" onclick="toggle_field_section(this)"><i class="fa fa-times fa-lg"></i></a>
        </span>
    }
</div>

Marathonrunners/Views/Setting/Success.cshtml
<span class="clk2raceSettingsListLabel"></span>
<div class="clk2raceSettingsListContent">
    Successfully Updated!!
    <input type="hidden" id="success" value=@Html.Raw(ViewBag.Value) />
</div>
<span class="clk2raceSettingsListGroupEdit">
    @if (@ViewBag.Location != null && @ViewBag.Location == true) {
        <a class="buttonlink" onclick=" toggle_field_section(this,'UserLocation') "><i class="fa fa-times fa-lg"></i></a>
    } else {
        <a class="buttonlink" onclick=" toggle_field_section(this) "><i class="fa fa-times fa-lg"></i></a>
    }
</span>

Marathonrunners/Views/Setting/UserLocation.cshtml
@model Marathonrunners.Models.UpdateViewModelUserLocation
<div id="userlocationupdate">
    @using (Ajax.BeginForm("UserLocationUpdate", "Setting", new AjaxOptions {
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "userlocationupdate",
        OnFailure = "update_ended",
        OnSuccess = "load_userlocation"
    })) {
        @Html.AntiForgeryToken()

        <ul class="forminsideul">
            <li>
                <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.Country)</span>
                <div class="clk2raceSettingsListContent">
                    @Html.DropDownListFor(model => model.Country, new List<SelectListItem>(), new { @name = "country", @id = "country", @onchange = "print_state('state', this.selectedIndex);" })
                    @Html.ValidationMessageFor(model => model.Country)
                    @Html.HiddenFor(model => model.HiddenCountry, new { @id = "hidden_country" })
                </div>
                <span class="clk2raceSettingsListGroupEdit">
                    <input class="buttonlink" type="submit" value="Update" />
                    <a class="buttonlink" onclick="toggle_field_section(this,'UserLocation')"><i class="fa fa-times fa-lg"></i></a>
                </span>
            </li>
            <li id="state_div">
                <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.State)</span>
                <div class="clk2raceSettingsListContent">
                    @Html.DropDownListFor(model => model.State, new List<SelectListItem>(), "Select State", new { @name = "state", @id = "state", @onchange = "print_city('city', this.selectedIndex);" })
                    @Html.ValidationMessageFor(model => model.State)
                    @Html.HiddenFor(model => model.HiddenState, new { @id = "hidden_state" })
                </div>
            </li>
            <li id="other_state_div" style="display:none">
                <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.OtherState)</span>
                <div class="clk2raceSettingsListContent">
                    @Html.TextBoxFor(model => model.OtherState, new { @name = "other_state", @id = "other_state", @placeholder = "Other State" })
                    @Html.ValidationMessageFor(model => model.OtherState)
                </div>
            </li>
            <li id="city_div">
                <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.City)</span>
                <div class="clk2raceSettingsListContent">
                    @Html.DropDownListFor(model => model.City, new List<SelectListItem>(), "Select City", new { @name = "city", @id = "city", @onchange = "$('#hidden_city').val($('#city :selected').text());" })
                    @Html.ValidationMessageFor(model => model.City)
                    @Html.HiddenFor(model => model.HiddenCity, new { @id = "hidden_city" })
                </div>
            </li>
            <li id="other_city_div" style="display:none">
                <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.OtherCity)</span>
                <div class="clk2raceSettingsListContent">
                    @Html.TextBoxFor(model => model.OtherCity, new { @name = "other_city", @id = "other_city", @placeholder = "Other City" })
                    @Html.ValidationMessageFor(model => model.OtherCity)
                    @Html.Hidden("othercity")
                </div>
            </li>
            <li>
                <span class="clk2raceSettingsListLabel">@Html.LabelFor(model => model.PostalCode)</span>
                <div class="clk2raceSettingsListContent">
                    @Html.TextBoxFor(model => model.PostalCode, new { @class = "nums", @name = "postcode", @id = "postcode", @placeholder = "Zip / Postal Code", @minlength = "4", @maxlength = "9" })
                    @Html.ValidationMessageFor(model => model.PostalCode)
                </div>
            </li>
        </ul>
    }
</div>