Marathonrunners/Controllers/AdminController.cs
using System;
using System.Web.Mvc;
using Marathonrunners.Core;
using Marathonrunners.Logging;
using Marathonrunners.Models;
using Marathonrunners.Utils;

namespace Marathonrunners.Controllers {
    public class AdminController : Controller {

        //private readonly IAdminRepository _adminRepository;
        //private readonly ILogger _logger;
        //public AdminController(IAdminRepository adminRepository, ILogger logger) {
        //    _logger = logger;
        //    _adminRepository = adminRepository;
        //}

        //// GET: Admin
        //public ActionResult Index() {
        //    return View();
        //}

        //public ActionResult ForceMailSender() {
        //    return View();
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult ForceMailSender(AdminViewModel model) {
        //    if (ModelState.IsValid) {
        //        var forceemailentry = new Core.Entities.ForceEmail();
        //        forceemailentry.EmailId = model.EmailId;
        //        forceemailentry.EventName = model.EventName;
        //        forceemailentry.Amount = model.Amount;
        //        forceemailentry.Mobile = model.Mobile;
        //        forceemailentry.TransactionId = model.TransactionId;
        //        forceemailentry.DateAndTime = DateTime.Now;

        //        var succeeModel = new TransactionSuccessfullModel() {
        //            Name = model.Name,
        //            Address = model.Address,
        //            EventName = model.EventName,
        //            Amount = model.Amount.ToString(),
        //            Mobile = model.Mobile.ToString(),
        //            TransactionId = model.TransactionId,
        //            DateAndTime = DateTime.Parse(model.DateAndTime)
        //        };
        //        var mailHtml = ViewToString.RenderViewToString(this.ControllerContext, "SuccessfulEmailConfirmation", succeeModel);
        //        var response = EmailHandler.RegistrationSuccessfull(model.EmailId, mailHtml);
        //        _adminRepository.AddForceEmail(forceemailentry);
        //        _logger.Info("ForceEmailSent|To:" + model.EmailId + "|By:" + User.Identity.Name + "|ResponseStatus:" + response.ResponseStatus + "|ResponseDescrip:" + response.StatusDescription);
        //        ViewBag.SuccessMessage = "Registration mail has been sent to " + model.EmailId;
        //        return View("Success");
        //    }
        //    return View(model);
        //}
    }
}

Marathonrunners/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using CsvHelper;
using EmailQueueSystem;
using marathonrunners.Models;
using marathonrunners.Models.DiscountService;
using marathonrunners.Utils;
using Marathonrunners.Core;
using Marathonrunners.Core.Entities;
using Marathonrunners.Logging;
using Marathonrunners.Models;
using Marathonrunners.Utils;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json.Linq;
using SMSIntegrationSystem;

namespace Marathonrunners.Controllers
{

    [Authorize]
    public class RegisterController : Controller
    {
        private readonly ILogger _logger;
        private readonly IAccountRepository _accountRepository;
        private readonly IEmailRepository _emailRepository;
        private readonly IEnumerable<string> _listOfPreviousYearBMUsers;

        public RegisterController(IAccountRepository accountRepository, ILogger logger, IEmailRepository emailRepository)
        {
            _accountRepository = accountRepository;
            _logger = logger;
            _emailRepository = emailRepository;
            _listOfPreviousYearBMUsers = GeLastYearBmUserFromCsv();

        }

        // GET: /Register/
        [AllowAnonymous]
        public ActionResult Index(string eventid)
        {
            switch (eventid)
            {

                case "IDBI_Training_Run2":
                    return View("IDBITraining2");

                case "SPBM_Promo_Run":
                    return View("SPBMPromoRun2017");

                case "SPBM_Luxor2017":
                    return View("SpbmLuxor");

                case "Hyd_StadRun2017":
                    return View("HUMStadiumRun");

                case "HUM5K_2017":
                    // return View("HUMLaunchRun");
                    return View("RegistrationClosed");

                case "IDBILIMHM_Training_Run":
                    //  return View("IDBITrainingRun17");
                    return View("RegistrationClosed");
                case "IDBI_Promo_Run":
                    return View("RegistrationClosed");

                case "spbm2017":
                    return View("SPBM17");

                case "idbimhm_2017":
                    return View("IDBIMHM2017");
                case "b10k_2017":
                    return View("B10KChallenge");
                case "sfa_2017":
                    return View("RegistrationClosed");
                case "nebrun_2017":
                    return View("NEBTestRun");
                case "tc_2017":
                    return View("RegistrationClosed");
                case "bm_2015":
                    return View("RegistrationClosed");
                case "spice_2015":
                    return View("RegistrationClosed");
                case "mysore_2015":
                    return View("RegistrationClosed");
                case "apr_2015":
                    return View("RegistrationClosed");
                case "spbm_stad_run17":
                    return View("SpbmStadium");
                case "bang1_2015":
                    return View("RegistrationClosed");
                case "bang2_2015":
                    return View("BANGALORE2");
                case "training5_2017":
                    return View("TRAINING5");
                case "sky_2015":
                    return View("RegistrationClosed");
                case "spice_fed_2015":
                    return View("RegistrationClosed");
                case "psnrun_2015":
                    return View("PSNRUN");
                case "bull_2015":
                    return View("Bull");
                case "coorg1_2015":
                    return View("RegistrationClosed");
                case "pedal_2015":
                    return View("RegistrationClosed");
                case "pedal_cxo_2015":
                    return View("RegistrationClosed");
                case "tracs_2016":
                    return View("RegistrationClosed");
                case "run_2015":
                    return View("RegistrationClosed");
                case "kkh_2015":
                    return View("RegistrationClosed");
                case "trot_workshop_2016":
                    return View("RegistrationClosed");
                case "tc_2016":
                    return View("RegistrationClosed");
                case "cwdr_2016":
                    return View("RegistrationClosed");
                case "rfh_2016":
                    return View("RegistrationClosed");
                case "kr_relay_2016":
                    return View("RegistrationClosed");
                case "trot_2016":
                    return View("TROT");
                case "brur_2016":
                    return View("RegistrationClosed");
                case "sfa_2016":
                    return View("RegistrationClosed");
                case "climb_2016":
                    return View("RegistrationClosed");
                default: return View();
            }
        }

        [RequireHttps]
        public ActionResult Enroll(string eventid)
        {
            var user = _accountRepository.GetUserById(User.Identity.Name);

            switch (eventid)
            {
                case "b10k_2017":
                    return View("EnrollB10KChallenge");
                case "sfa_2017":
                    return View("RegistrationClosed");
                case "tc_2017":
                    return View("RegistrationClosed");

                case "bm_2015":
                    ViewBag.EventId = eventid;
                    return View("RegistrationClosed");
                case "spice_2015":
                    return View("RegistrationClosed");
                case "mysore_2015":
                    return View("RegistrationClosed");
                case "run_2015":
                    return View("RegistrationClosed");
                //case "pune_2015":
                //case "mum_2015":
                //case "coch_2015":
                //case "delhi_2015":
                case "bang1_2015":
                    return PaymentPromo(eventid);
                case "bang2_2015":
                    return PaymentPromo(eventid);
                case "training5_2017":
                    return PaymentPromo(eventid);
                case "sky_2015":
                    return View("RegistrationClosed");
                case "psnrun_2015":
                    return View("RegistrationClosed");
                case "bull_2015":
                    return View("RegistrationClosed");
                case "tracs_2015":
                    return View("RegistrationClosed");
                case "coorg1_2015":
                    return View("RegistrationClosed");
                case "sfa_2016":
                    return View("EnrollStridesforAutism", user);
                default: return View("Index");
            }
        }

        //TODO: make it generic
        [RequireHttps]
        public ActionResult PaymentPromo(string eventId)
        {
            var eventNames = new Dictionary<string, string>(){
                {"promo1_2015", "SPBM 2015 - Hyderabad Promo Run"},
                {"pune_2015", "SPBM 2015 - Pune Promo Run"},
                {"mum_2015", "SPBM 2015 - Mumbai Promo Run"},
                {"coch_2015", "SPBM 2015 - Cochin Promo Run"},
                {"gur_2015", "SPBM 2015 - Gurgaon Promo Run"},
                {"bang2_2015", "SPBM 2015 - Taper Down with Yoga"},
                {"training5_2017", "IDBI Federal New Delhi Marathon Adidas Runners X Training Run – 5"},
                  {"bang1_2015", "SPBM 2015 - Family Fun Event"}
            };
            var userid = User.Identity.Name;
            if (userid == null)
            {
                return RedirectToAction("LogOff", "Account");
            }
            var runreg = new BMUserRunRegistration2015()
            {
                FinalPrice = 0,
                Status = true,
                UserId = userid,
                RegistrationDate = DateTime.Now,
                RunCategoryId = eventNames[eventId],
            };
            if (_accountRepository.AlreadyRegisteredBM2015PromoRun(runreg))
            {
                ViewBag.ErrorMessage = "You have already registered for this event!";
                return View("Error");
            }
            int dbid = _accountRepository.RegisterBM2015UserRun(runreg);
            var user = _accountRepository.GetUserById(userid);
            var transactionId = "C2R-" + dbid;
            SendSuccessConfirmationMail(user, eventId, runreg.RunCategoryId, transactionId, 0);
            ViewBag.TransactionId = transactionId;
            return PartialView("TransactionSuccessfull");
        }

        [HttpPost]
        [RequireHttps]
        public ActionResult PaymentInit(PayInitJsonData jsoninfo)
        {
            var eventid = jsoninfo.EventId;
            var user = _accountRepository.GetUserById(User.Identity.Name);
            var payInit = new PayInitViewModel();

            int eventSelection;
            PayInitViewModel payinit2;
            switch (eventid)
            {
                // TODO: Get all these details from the database

                case "b10k_2017":
                    var eventData = EventData.GetEventDetails(eventid);
                    eventSelection = jsoninfo.EventType;
                    payinit2 = new PayInitViewModel()
                    {
                        Title = eventData.EventTitle,
                        DateOfEvent = eventData.DataOfEvent,
                        EmailId = user.EmailId,
                        FullName = user.FirstName + " " + user.LastName,
                        EventId = eventid,
                        Location = eventData.Location,
                        EventType = eventData.EventCategoryList[eventSelection - 1].EventTitle,

Marathonrunners/Views/Admin/AddEvent.cshtml
@{
    ViewBag.Title = "Admin Module";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Click2race :: Admin Page</title>
    <link rel="stylesheet" href="../Contents-New/admin/css/components.css">
    <link rel="stylesheet" href="../Contents-New/admin/css/icons.css">
    <link rel="stylesheet" href="../Contents-New/admin/css/responsee.css">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="../Contents-New/admin/js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="../Contents-New/admin/js/jquery-ui.min.js"></script>
    <!----font-Awesome----->
    <link rel="stylesheet" href="../Contents-New/admin/css/font-awesome.min.css">
    <!----font-Awesome----->
    <!-- date picker starts -->
    <!--

        Copyright 2009 Itamar Arjuan
        jsDatePick is distributed under the terms of the GNU General Public License.

        ****************************************************************************************

        Copy paste these 2 lines of code to every page you want the calendar to be available at
    -->
    <link rel="stylesheet" type="text/css" media="all" href="../Contents-New/admin/jsDatePick_ltr.min.css" />
    <!--
        OR if you want to use the calendar in a right-to-left website
        just use the other CSS file instead and don't forget to switch g_jsDatePickDirectionality variable to "rtl"!

        <link rel="stylesheet" type="text/css" media="all" href="../Contents-New/admin/jsDatePick_ltr.css" />
    -->
    <script type="text/javascript" src="../Contents-New/admin/jsDatePick.min.1.3.js"></script>
    <!--
        After you copied those 2 lines of code , make sure you take also the files into the same folder :-)
        Next step will be to set the appropriate statement to "start-up" the calendar on the needed HTML element.

        The first example of Javascript snippet is for the most basic use , as a popup calendar
        for a text field input.
    -->
    <script type="text/javascript">
	window.onload = function(){
		new JsDatePick({
			useMode:2,
			target:"inputField",
			dateFormat:"%d-%M-%Y"
			/*selectedDate:{				This is an example of what the full configuration offers.
				day:5,						For full documentation about these settings please see the full version of the code.
				month:9,
				year:2006
			},
			yearsRange:[1978,2020],
			limitToToday:false,
			cellColorScheme:"beige",
			dateFormat:"%m-%d-%Y",
			imgPath:"https://clicktorace.blob.core.windows.net/portalimages/",
			weekStartDay:1*/
		});
	};
    </script>

    <!-- date picker ends -->


</head>
<body class="size-1140">
    <!-- TOP NAV WITH LOGO -->
    <header>
        <nav>
            <div class="line">
                <div class="s-12 l-2"> <a href="index.html"><img class="s-5 l-12 center" src="https://clicktorace.blob.core.windows.net/portalimages/logo.png"></a> </div>
                <div class="top-nav s-12 l-10 right">
                    <p class="nav-text">User Name</p>
                    <ul class="right">
                        <li><a>User Name : </a></li>
                        <li><a><i class="fa fa-envelope-o" aria-hidden="true"></i></a></li>
                        <li><a><i class="fa fa-bell-o" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <!-- ASIDE NAV AND CONTENT -->
    <div class="line">
        <div class="box  margin-bottom">
            <div class="margin">
                <!-- ASIDE NAV 1 -->
                <aside class="s-12 l-3">
                    <h3>Admin</h3>
                    <div class="aside-nav">
                        <ul>
                            <li style="padding:15px;">Dashboard</li>
                            <li> <a>Events</a></li>
                            <li> <a>Organisers</a> </li>
                            <li><a>Users</a></li>
                        </ul>
                    </div>
                </aside>
                <!-- CONTENT -->
                <section class="s-12 l-9">
                    <h1>Add Event</h1>
                    <form class="customform" action="">
                        <div class="line">
                            <div class="margin">
                                <div class="s-12 l-4">
                                    <div class="box-dark">
                                        <input type="text" id="name" placeholder="Enter the Event name">
                                    </div>
                                </div>
                                <div class="s-12 l-4">
                                    <div class="box-dark">
                                        <input type="text" size="12" id="inputField" placeholder="select the date" />
                                    </div>
                                </div>
                                <div class="s-12 l-4">
                                    <div class="box-dark"><a class="button rounded-full-btn cancel-btn margin-bottom" href="#"><i class="icon-check"></i> Add Event</a> </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="line">
                        <div class="l-12 s-12">
                            <table>
                                <thead>
                                    <tr>
                                        <th>Event Name</th>
                                        <th>Organiser</th>
                                        <th>City</th>
                                        <th>Participant Count</th>
                                        <th>Event Type</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>New Delhi Marathon</td>
                                        <td>Snap Fitness</td>
                                        <td>Bengaluru </td>
                                        <td>1000</td>
                                        <td>Running</td>
                                        <td>Edit / Delete / View</td>
                                    </tr>
                                    <tr>
                                        <td>New Delhi Marathon</td>
                                        <td>Snap Fitness</td>
                                        <td>Bengaluru </td>
                                        <td>1000</td>
                                        <td>Running</td>
                                        <td>Edit / Delete / View</td>
                                    </tr>
                                    <tr>
                                        <td>New Delhi Marathon</td>
                                        <td>Snap Fitness</td>
                                        <td>Bengaluru </td>
                                        <td>1000</td>
                                        <td>Running</td>
                                        <td>Edit / Delete / View</td>
                                    </tr>
                                    <tr>
                                        <td>New Delhi Marathon</td>
                                        <td>Snap Fitness</td>
                                        <td>Bengaluru </td>
                                        <td>1000</td>
                                        <td>Running</td>
                                        <td>Edit / Delete / View</td>
                                    </tr>
                                    <tr>
                                        <td>New Delhi Marathon</td>
                                        <td>Snap Fitness</td>
                                        <td>Bengaluru </td>
                                        <td>1000</td>
                                        <td>Running</td>
                                        <td>Edit / Delete / View</td>
                                    </tr>
                                    <tr>
                                        <td>New Delhi Marathon</td>
                                        <td>Snap Fitness</td>
                                        <td>Bengaluru </td>
                                        <td>1000</td>
                                        <td>Running</td>
                                        <td>Edit / Delete / View</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </section>
                <!-- ASIDE NAV 2 -->

            </div>
        </div>
    </div>
    <!-- FOOTER -->

    <script type="text/javascript" src="../Contents-New/admin/js/responsee.js"></script>
</body>
</html>

Marathonrunners/Views/Admin/ForceMailSender.cshtml
@model Marathonrunners.Models.AdminViewModel
@{
    ViewBag.Title = "Force Mail Sender";
}

<div id="mainBody">
    <div class="row">
        <div id="headerpage">
            <h3 class="center_header">Force Mail Sender</h3>
            <div class="well" style="height: 700px">
                <div class="register">
                    @using (Html.BeginForm("ForceMailSender", "Admin", FormMethod.Post, new { @id = "reg_form", @class = "form-horizontal", @role = "form" })) {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary()

                        <div class="control-group">
                            @Html.LabelFor(model => model.EmailId, new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextBoxFor(model => model.EmailId, new {
                               @class = "chars", @name = "emailid", @id = "emailid",
                               @placeholder = "Email Id", @autocomplete = "off"
                           })
                                @Html.ValidationMessageFor(model => model.EmailId)
                            </div>
                        </div>
                        <div class="control-group">
                            @Html.LabelFor(model => model.Name, new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextBoxFor(model => model.Name, new {
                               @class = "chars", @name = "name", @id = "name",
                               @placeholder = "Name", @autocomplete = "off"
                           })
                                @Html.ValidationMessageFor(model => model.Name)
                            </div>
                        </div>
                        <div class="control-group">
                            @Html.LabelFor(model => model.Address, new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextBoxFor(model => model.Address, new {
                               @name = "address", @id = "address",
                               @placeholder = "Address", @autocomplete = "off"
                           })
                                @Html.ValidationMessageFor(model => model.Address)
                            </div>
                        </div>
                        <div class="control-group">
                            @Html.LabelFor(model => model.EventName, new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextBoxFor(model => model.EventName, new {
                               @name = "eventname", @id = "eventname",
                               @placeholder = "EventName", @autocomplete = "off"
                           })
                                @Html.ValidationMessageFor(model => model.EventName)
                            </div>
                        </div>
                        <div class="control-group">
                            @Html.LabelFor(model => model.Amount, new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextBoxFor(model => model.Amount, new {
                               @name = "amount", @id = "amount",
                               @placeholder = "Amount", @autocomplete = "off"
                           })
                                @Html.ValidationMessageFor(model => model.Amount)
                            </div>
                        </div>
                        <div class="control-group">
                            @Html.LabelFor(model => model.Mobile, new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextBoxFor(model => model.Mobile, new {
                               @name = "mobile", @id = "mobile",
                               @placeholder = "Mobile", @autocomplete = "off"
                           })
                                @Html.ValidationMessageFor(model => model.Mobile)
                            </div>
                        </div>
                        <div class="control-group">
                            @Html.LabelFor(model => model.TransactionId, new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextBoxFor(model => model.TransactionId, new {
                               @name = "transactionid", @id = "transactionid",
                               @placeholder = "TransactionId", @autocomplete = "off"
                           })
                                @Html.ValidationMessageFor(model => model.TransactionId)
                            </div>
                        </div>
                        <div class="control-group">
                            @Html.LabelFor(model => model.DateAndTime, new { @class = "control-label" })
                            <div class="controls">
                                @Html.TextBoxFor(model => model.DateAndTime, new {
                               @name = "dateandtime", @id = "dateandtime",
                               @placeholder = "Date and Time", @autocomplete = "off"
                           })
                                @Html.ValidationMessageFor(model => model.DateAndTime)
                            </div>
                        </div>
                        <div style="text-align: center">
                            <input class="btn btn-large btn-success" type="submit" id="submitbtn" value="Register" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Marathonrunners/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Admin Module";
    Layout = "~/Views/Shared/_LayoutAdminNew.cshtml";
}

<h1>Page Index</h1>
<ul>
    <li><a href="~/Account/Login">Login Page</a></li>
    <li><a href="~/Account/AddEvent">Add Event page</a></li>
    <li><a href="~/Account/EventDetails">Event Details Page</a></li>

</ul>

Marathonrunners/Views/Admin/Register.cshtml
@{
    ViewBag.Title = "Admin Module";
    Layout = "~/Views/Shared/_LayoutAdminNew.cshtml";
}

<h1>Register</h1>
<form class="customform" action="" style="text-align:center">
    <div class="line"> </div>
    <br>
    <br>

</form>