Marathonrunners/Models/PayInitViewModel.cs
namespace Marathonrunners.Models {
    public class PayInitViewModel {
        public string EmailId { get; set; }
        public string FullName { get; set; }
        public string EventId { get; set; }
        public string Title { get; set; }
        public string EventType { get; set; }
        public int Fee { get; set; }
        public string DateOfEvent { get; set; }
        public string Location { get; set; }
        public bool Student { get; set; }
        public bool Discount { get; set; }
        public int DiscountAmount { get; set; }
        public string DiscountPurpose { get; set; }
        public int? Donation { get; set; }
        public string DonationTo { get; set; }
        public string FedDetails { get; set; }
    }

    public class BmPayInitViewModel : PayInitViewModel {
        public string BestRunTiming { get; set; }
        public string TimingHyperLink { get; set; }
        public string Distance { get; set; }
        public string EventName { get; set; }
    }
}

Marathonrunners/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using CsvHelper;
using EmailQueueSystem;
using marathonrunners.Models;
using marathonrunners.Models.DiscountService;
using marathonrunners.Utils;
using Marathonrunners.Core;
using Marathonrunners.Core.Entities;
using Marathonrunners.Logging;
using Marathonrunners.Models;
using Marathonrunners.Utils;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json.Linq;
using SMSIntegrationSystem;

namespace Marathonrunners.Controllers
{

    [Authorize]
    public class RegisterController : Controller
    {
        private readonly ILogger _logger;
        private readonly IAccountRepository _accountRepository;
        private readonly IEmailRepository _emailRepository;
        private readonly IEnumerable<string> _listOfPreviousYearBMUsers;

        public RegisterController(IAccountRepository accountRepository, ILogger logger, IEmailRepository emailRepository)
        {
            _accountRepository = accountRepository;
            _logger = logger;
            _emailRepository = emailRepository;
            _listOfPreviousYearBMUsers = GeLastYearBmUserFromCsv();

        }

        // GET: /Register/
        [AllowAnonymous]
        public ActionResult Index(string eventid)
        {
            switch (eventid)
            {

                case "IDBI_Training_Run2":
                    return View("IDBITraining2");

                case "SPBM_Promo_Run":
                    return View("SPBMPromoRun2017");

                case "SPBM_Luxor2017":
                    return View("SpbmLuxor");

                case "Hyd_StadRun2017":
                    return View("HUMStadiumRun");

                case "HUM5K_2017":
                    // return View("HUMLaunchRun");
                    return View("RegistrationClosed");

                case "IDBILIMHM_Training_Run":
                    //  return View("IDBITrainingRun17");
                    return View("RegistrationClosed");
                case "IDBI_Promo_Run":
                    return View("RegistrationClosed");

                case "spbm2017":
                    return View("SPBM17");

                case "idbimhm_2017":
                    return View("IDBIMHM2017");
                case "b10k_2017":
                    return View("B10KChallenge");
                case "sfa_2017":
                    return View("RegistrationClosed");
                case "nebrun_2017":
                    return View("NEBTestRun");
                case "tc_2017":
                    return View("RegistrationClosed");
                case "bm_2015":
                    return View("RegistrationClosed");
                case "spice_2015":
                    return View("RegistrationClosed");
                case "mysore_2015":
                    return View("RegistrationClosed");
                case "apr_2015":
                    return View("RegistrationClosed");
                case "spbm_stad_run17":
                    return View("SpbmStadium");
                case "bang1_2015":
                    return View("RegistrationClosed");
                case "bang2_2015":
                    return View("BANGALORE2");
                case "training5_2017":
                    return View("TRAINING5");
                case "sky_2015":
                    return View("RegistrationClosed");
                case "spice_fed_2015":
                    return View("RegistrationClosed");
                case "psnrun_2015":
                    return View("PSNRUN");
                case "bull_2015":
                    return View("Bull");
                case "coorg1_2015":
                    return View("RegistrationClosed");
                case "pedal_2015":
                    return View("RegistrationClosed");
                case "pedal_cxo_2015":
                    return View("RegistrationClosed");
                case "tracs_2016":
                    return View("RegistrationClosed");
                case "run_2015":
                    return View("RegistrationClosed");
                case "kkh_2015":
                    return View("RegistrationClosed");
                case "trot_workshop_2016":
                    return View("RegistrationClosed");
                case "tc_2016":
                    return View("RegistrationClosed");
                case "cwdr_2016":
                    return View("RegistrationClosed");
                case "rfh_2016":
                    return View("RegistrationClosed");
                case "kr_relay_2016":
                    return View("RegistrationClosed");
                case "trot_2016":
                    return View("TROT");
                case "brur_2016":
                    return View("RegistrationClosed");
                case "sfa_2016":
                    return View("RegistrationClosed");
                case "climb_2016":
                    return View("RegistrationClosed");
                default: return View();
            }
        }

        [RequireHttps]
        public ActionResult Enroll(string eventid)
        {
            var user = _accountRepository.GetUserById(User.Identity.Name);

            switch (eventid)
            {
                case "b10k_2017":
                    return View("EnrollB10KChallenge");
                case "sfa_2017":
                    return View("RegistrationClosed");
                case "tc_2017":
                    return View("RegistrationClosed");

                case "bm_2015":
                    ViewBag.EventId = eventid;
                    return View("RegistrationClosed");
                case "spice_2015":
                    return View("RegistrationClosed");
                case "mysore_2015":
                    return View("RegistrationClosed");
                case "run_2015":
                    return View("RegistrationClosed");
                //case "pune_2015":
                //case "mum_2015":
                //case "coch_2015":
                //case "delhi_2015":
                case "bang1_2015":
                    return PaymentPromo(eventid);
                case "bang2_2015":
                    return PaymentPromo(eventid);
                case "training5_2017":
                    return PaymentPromo(eventid);
                case "sky_2015":
                    return View("RegistrationClosed");
                case "psnrun_2015":
                    return View("RegistrationClosed");
                case "bull_2015":
                    return View("RegistrationClosed");
                case "tracs_2015":
                    return View("RegistrationClosed");
                case "coorg1_2015":
                    return View("RegistrationClosed");
                case "sfa_2016":
                    return View("EnrollStridesforAutism", user);
                default: return View("Index");
            }
        }

        //TODO: make it generic
        [RequireHttps]
        public ActionResult PaymentPromo(string eventId)
        {
            var eventNames = new Dictionary<string, string>(){
                {"promo1_2015", "SPBM 2015 - Hyderabad Promo Run"},
                {"pune_2015", "SPBM 2015 - Pune Promo Run"},
                {"mum_2015", "SPBM 2015 - Mumbai Promo Run"},
                {"coch_2015", "SPBM 2015 - Cochin Promo Run"},
                {"gur_2015", "SPBM 2015 - Gurgaon Promo Run"},
                {"bang2_2015", "SPBM 2015 - Taper Down with Yoga"},
                {"training5_2017", "IDBI Federal New Delhi Marathon Adidas Runners X Training Run – 5"},
                  {"bang1_2015", "SPBM 2015 - Family Fun Event"}
            };
            var userid = User.Identity.Name;
            if (userid == null)
            {
                return RedirectToAction("LogOff", "Account");
            }
            var runreg = new BMUserRunRegistration2015()
            {
                FinalPrice = 0,
                Status = true,
                UserId = userid,
                RegistrationDate = DateTime.Now,
                RunCategoryId = eventNames[eventId],
            };
            if (_accountRepository.AlreadyRegisteredBM2015PromoRun(runreg))
            {
                ViewBag.ErrorMessage = "You have already registered for this event!";
                return View("Error");
            }
            int dbid = _accountRepository.RegisterBM2015UserRun(runreg);
            var user = _accountRepository.GetUserById(userid);
            var transactionId = "C2R-" + dbid;
            SendSuccessConfirmationMail(user, eventId, runreg.RunCategoryId, transactionId, 0);
            ViewBag.TransactionId = transactionId;
            return PartialView("TransactionSuccessfull");
        }

        [HttpPost]
        [RequireHttps]
        public ActionResult PaymentInit(PayInitJsonData jsoninfo)
        {
            var eventid = jsoninfo.EventId;
            var user = _accountRepository.GetUserById(User.Identity.Name);
            var payInit = new PayInitViewModel();

            int eventSelection;
            PayInitViewModel payinit2;
            switch (eventid)
            {
                // TODO: Get all these details from the database

                case "b10k_2017":
                    var eventData = EventData.GetEventDetails(eventid);
                    eventSelection = jsoninfo.EventType;
                    payinit2 = new PayInitViewModel()
                    {
                        Title = eventData.EventTitle,
                        DateOfEvent = eventData.DataOfEvent,
                        EmailId = user.EmailId,
                        FullName = user.FirstName + " " + user.LastName,
                        EventId = eventid,
                        Location = eventData.Location,
                        EventType = eventData.EventCategoryList[eventSelection - 1].EventTitle,

Marathonrunners/Views/Register/CLIMB.cshtml
@{
    ViewBag.Title = "CLIMB against sexual abuse";
}
<div id="mainBody">
    <div class="row">
        <div id="headerpage">
            <h3 class="center_header">CLIMB against sexual abuse</h3>
            <div class="well">
                <div id="logo" style="text-align: center;">
                    @*<img src="https://clicktorace.blob.core.windows.net/portalimages/trot_slider.jpg" alt="cwdrpic" class="img-rounded" />*@
                </div>
                <br />
                <br />
                <div style="text-align: center; font-size: large">
                    <span id="enroll_link"><a href=@Url.Action("FastLane", "Register", new RouteValueDictionary() {{"eventid", "climb_2016"}}) role="button">Continue</a></span>
                </div>
                <div id="aboutevent">
                    <h4>About Event</h4>
                    <p><strong>CLIMB against sexual abuse!</strong></p><br />
                    <p>CLIMB is a global non-profit organisation, trying to break the silence on sexual violence and creating a powerful movement of change. We are continuously expanding with our presence in over 18 countries. Our team of over 30 members serves the borderless world, spreading awareness, undoing the stigma, and changing the social mindset. We believe in building a better society, which not only will inspire social citizens to celebrate a survivor’s triumph with love and compassion but will also survivors to help others in their healing journey.</p>
                    <br />
                    <p><strong>Odanadi Seva Samithi</strong></p>
                    <p>Odanadi is an NGO based in Mysore. Odanadi addresses all forms of sexual violence against women and children, with special focus on human trafficking. They have adopted a holistic approach to combat sexual violence through prevention, rescue, rehabilitation, awareness and training programs.</p>
                    <br />
                    <p>It is a fund raising event. CLIMB will be taking 18 individuals from different parts of the world on an expedition to Kilinajaro. Kilimanjaro is more than just a highest mountain in Africa – it is a symbol of victory for survivors to show their appreciation of life and ability to shatter convention. The climb aims to change the notion of the survivors being victims and instead encourages survivors to come forward and celebrate their conquest. With our Kilimanjaro climb and subsequent video, we aim to reach more than 10 million lives. </p>
                </div>
                <hr>
                <div id="eventdate">
                    <h5>Event Date -- June 26th, 2016 - Sunday</h5>
                    <h5>Event Location -- Chamundi Hill footsteps, Mysuru </h5>
                    <h5>Race Details (Distance/Fee/Start Time) - It is a fund raising event. The participants have to climb the Chamundi hill steps. (1000 steps and it concludes at Mahishasura point, where the participants will be addressed by the event organizers to speak about the cause and spread the message and create awareness. The event will be flagged off at 6.30 am by the MP Shri Prathap Simha and Actress Nidhi Subbaiah. Participants are expected to assemble at start point at 6 am. There will be free tender coconut distribution at the end point for all participants, volunteers and organisers, along with water aid stations.</h5>
                    <h5>Prizes if any – No prizes</h5>
                    <h5>Age Category or any race specific rules – Open to all age groups.</h5>
                </div>
                <hr>
                <div style="text-align: center; font-size: large">
                    <span id="enroll_link"><a href=@Url.Action("FastLane", "Register", new RouteValueDictionary() {{"eventid", "climb_2016"}}) role="button">Continue</a></span>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    #enroll_link a:hover {
        color: orangered;
    }
</style>

Marathonrunners/Views/Register/COORG1.cshtml
@{
    ViewBag.Title = "4X4 Offroader Workshop";
}
@section ExtendedMetaInformation {
    <meta name="description" content="4x4 Offroader an event by Coorg Adventure Club ">
    <meta name="keywords" content="Offroading,adventure,jeep,4X4,Coorg">
}
<div id="mainBody">
    <div class="row">
        <div id="headerpage">
            <h3 class="center_header">4x4 Offroader Workshop </h3>
            <div class="well">
                <div id="logo" style="text-align:center;">
                    <img src="https://clicktorace.blob.core.windows.net/portalimages/coorg1_banner.jpg" alt="psnrun_banner" class="img-rounded" />
                </div>
                <br />
                <br />
                <div style="text-align: center;font-size: large">
                    <span id="enroll_link"><a href=@Url.Action("Enroll", "Register", new RouteValueDictionary() { { "eventid", "coorg1_2015" } }) role="button">Continue</a></span>
                </div>
                <div id="aboutevent">
                    <br />
                    <h4>Itenerary</h4>
                    <b>Day 1</b>
                    <p>1. Arrive at COORG ADVENTURE CLUB by 4</p>
                    <p>2. Briefing,Bonfire and Dinner from 7 pm onwards.</p>

                    <b>DAY 2</b>
                    <p>1.Breakfast at 6:30 am</p>
                    <p>2. 7 am Drive (4X4)</p>
                    <p>3.  1 pm Lunch</p>
                    <p>4.  4 pm Obstacle course/Football</p>
                    <p>5.  Dinner,Bonfire and Entertainment 7 pm onwards</p>

                    <b>DAY 3</b>
                    <p>1.  Breakfast 7 am onwards</p>
                    <p>2. Checkout after breakfast.</p>
                </div>
                <br />
                <h4>About Organisers</h4>
                <p>Event By :  Coorg Adventure Club </p>
                <hr>
                <div id="starttimeandroutedetails">
                    <h4>Event Date:</h4><h5 style="color:orangered"> 24th-26th July, 2015</h5>
                    <h4>Event Location:</h4><h5 style="color:orangered"> COORG ADVENTURE CLUB,VIRAJPET</h5>
                </div>
                <hr>
                <div id="typesofevent">
                    <h4>Pricing</h4>
                    <style>
                        table, th, td {
                            border-collapse: collapse;
                            border: 1px solid black;
                        }

                        th, td {
                            padding: 5px;
                        }
                    </style>
                    <table>
                        <tr>
                            <th>Package</th>
                            <th>Registration fee</th>
                            <th>Inclusions</th>
                        </tr>
                        <tr>
                            <td>Drive Only Package</td>
                            <td>1000/- per person</td>
                            <td>This includes lunch</td>
                        </tr>
                        <tr>
                            <td>Club Package</td>
                            <td>4999/- per person</td>
                            <td>This includes all meals and stay at the dormitory in the  COORG ADVENTURE CLUB</td>

                        </tr>
                        <tr>
                            <td>Premium Package</td>
                            <td>9999/- per person (On a twin sharing occupancy)</td>
                            <td>This includes stay and breakfast at Ambatty Greens Resort in the deluxe rooms.All other meals will be at the COORG ADVENTURE CLUB</td>
                        </tr>
                    </table>
                </div>
                <hr>
                <div style="text-align: center;font-size: large">
                    <span id="enroll_link"><a href=@Url.Action("Enroll", "Register", new RouteValueDictionary() { { "eventid", "coorg1_2015" } }) role="button">Continue</a></span>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    #enroll_link a:hover {
        color: orangered;
    }
</style>
<style>
    #terms_hover a:hover {
        color: orangered;
    }
</style>

Marathonrunners/Views/Register/Index.cshtml
@{
    ViewBag.Title = "Not Found";
}
<div id="mainBody">
    <div class="row">
        <div id="headerpage">
            <h3 class="center_header">Oops!!</h3>
            <div class="well" style="height: 700px">
                <div class="register">
                    <h2>We could not find what you are searching for :(</h2>
                </div>
            </div>
        </div>
    </div>
</div>

Marathonrunners/Views/Register/Mysore.cshtml
@{
    ViewBag.Title = "Chamundi Hill Challenge";
}
<div id="mainBody">
    <div class="row">
        <div id="headerpage">
            <h3 class="center_header">Chamundi Hill Challenge</h3>
            <div class="well">
                <div id="logo" style="text-align:center;">
                    <img src="https://clicktorace.blob.core.windows.net/portalimages/mysore_banner.jpg" alt="Chamundi Hill Challenge" class="img-rounded" />
                </div>
                <br/>
                <br/>
                <div style="text-align: center;font-size: large">
                    <span id="enroll_link"><a href=@Url.Action("Enroll","Register",new RouteValueDictionary(){{"eventid","mysore_2015"}}) role="button">Continue</a></span>
                </div>
                <div id="aboutevent">
                    <br />
                    <h4>About Event and the Organisers</h4>
                    <p>
                        Mysuru City still has that old world charm and a relaxed atmosphere! The Mysuru Palace, the Old Architectural Buildings, The Mysuru Zoo, Jagan Mohan Palace, Lalitha Mahal Palace, Manasa Gangotri and of course the Chamundi Hill.
                        <br/>
                        Mysoorunners is a group conceptualised by runners in Mysuru for the joy of inducting more runners into the community, guide them on the right way to go about it, promote fitness through running and share the joy of running!
                        This has taken us a step further to sharing our joy of running, the beautiful and majestic Chamundi Hill located in the middle of town and still maintaining it's own calm and serenity.
                        <br/>    
                        The creation of Chamundi Hill Challenge took it's roots from those thoughts and will become reality on 22 November 2015. We take great pleasure in sharing our joys of running on and around the winding roads, inclines, undulations, trails and the wonderful experience of ascending and descending age old steps leading to the Chamundeshwari Temple.
                        So come, enjoy and celebrate the beautiful Chamundi Hill with a choice of the Challenge 21, Tough10 or the Easy 5 runs.
                        <br/>
                        Challenge 21 and Tough 10 will be timed races.
                        Challenge 21 will comprise 2 loops of 6.5K Road, Ascend, Descend and Run 130 Steps and Cobbled Track and 4K Trail Run.
                        <br/>
                        Tough 10 will be the same route but just 1 loop.
                        <br/>
                        Easy 5 will be a 2.5K uphill and 2.5K downhill run and will not be timed.

                        All runners in all 3 categories will get Finisher Medals and T Shirts. At the end of the race breakfast will be served as well.
                    </p>
                </div>
                <hr>
                <div id="starttimeandroutedetails">
                    <h4>Event Date:</h4><h5 style="color:orangered"> 22nd November,2015</h5>
                    <h4>Event Time:</h4><h5 style="color:orangered">6am</h5>
                    <h4>Event Location:</h4><h5 style="color:orangered">Chamundi Hills, Mysore</h5>
                </div>
                <hr>
                <div id="typesofevent">
                    <h4>Race Details</h4>
                    <style>
                        table, th, td {
                            border-collapse: collapse;
                            border: 1px solid black;
                        }

                        th, td {
                            padding: 5px;
                        }
                    </style>
                    <table>
                        <tr>
                            <th>Distance</th>
                            <th>Registration Fee</th>
                        </tr>
                        <tr>
                            <td>Challenge 21k</td>
                            <td>900/-</td>
                        </tr>
                        <tr>
                            <td>Tough 10k</td>
                            <td>800/-</td>
                        </tr>
                        <tr>
                            <td>Easy 5k</td>
                            <td>500/-</td>
                        </tr>
                    </table>
                    <br/>
                    <p>Note : Race day T shirts and medals and Post Race breakfast will be provided to all the registered runners</p>
                    <p>If you are trying to make payment through International Card(Foreign Card), then please contact support@click2race.in</p>
                </div>
                <hr>
                <div style="text-align: center;font-size: large">
                    <span id="enroll_link"><a href=@Url.Action("Enroll","Register",new RouteValueDictionary(){{"eventid","mysore_2015"}}) role="button">Continue</a></span>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
    #enroll_link a:hover {
        color: orangered;
    }
</style>

Marathonrunners/Views/Register/RFH.cshtml
@{
    ViewBag.Title = "Rupee For Humanty Run";
}
@section ExtendedMetaInformation {
    <meta name="description" content="Rupee for Humanity run">
    <meta name="keywords" content="Running, EGL, Fitness, Women, Run, Fit, Cycle, Exercise, charity">
}
<div id="mainBody">
    <div class="row">
        <div id="headerpage">
            <h3 class="center_header">Rupee For Humanity</h3>
            <div class="well">
                <div id="logo" style="text-align:center;">
                    <img src="https://click2race.blob.core.windows.net:443/portalimages/rfhbanner2016.jpg" alt="rfh_banner" class="img-rounded" />
                </div>
                <br />
                <br />
                <div style="text-align: center;font-size: large">
                    <span id="enroll_link"><a href=@Url.Action("FastLane", "Register", new RouteValueDictionary() { { "eventid", "rfh_2016" } }) role="button">Continue</a></span>
                </div>
                <div id="aboutevent">
                    <br />
                    <h4>About Event</h4>
                    <p>Rupee For Humanity (RFH) is an online NGO registered with the Government, started by a bunch of engineers having passion to work for the country and its development. It is a non-profit organization aimed at eradicating illiteracy from the roots and making India rise up high in the ladder of developed nations.</p>
                    <p>RFH provides :-</p>
                    <ul>
                        <li>
                            Right to education for every child
                        </li><li>
                                 Food, medical care and healthy atmosphere for the poor and needy.      
                        </li>
                    </ul>
                    <p>
                        For more information about our NGO, please visit the below link
                        https://www.facebook.com/RupeeForHumanity .
                        RFH has initiated a program - "Shikshakaar - Shikshan ka adhikaar", a step to eradicate illiteracy in India. We believe education is the backbone of any developing country. Driven by this belief, we provide free education for meritorious, poor, needy and orphaned children from NGOs, Government schools and various other sources.

                        As a part of this initiative, we conducted ‘RFH 10K Run - Run for Literacy’ last year at Cubbon park, Bangalore and from the contributions of kind hearts like you , we were able to sponsor education for 52 underprivileged kids from various places including stationary, books and school uniforms
                        We are proud to host the event again this year "RFH 10K Run - Run for Literacy"

                        For any more information about organizers or for sponsorships, you can reach out Raghavendra TN +91-9164358027 and Ashish SR +91-9743088879
                    </p>
                </div>
                <br />
                <hr>
                <div id="starttimeandroutedetails">
                    <h4>Event Date:</h4><h5 style="color:orangered"> 24th April, 2016</h5>
                    <h4>Event Location:</h4><h5 style="color:orangered">Cubbon Park, Bangalore</h5>
                    <h4>Event Timing:</h4><h5 style="color:orangered">06:00 am</h5>
                </div>
                <hr>
                <div id="typesofevent">
                    <h4>Race Details</h4>
                    <style>
                        table, th, td {
                            border-collapse: collapse;
                            border: 1px solid black;
                        }

                        th, td {
                            padding: 5px;
                        }
                    </style>
                    <table>
                        <tr>
                            <th>Distance</th>
                            <th>Racer Kit</th>
                            <th>Registration fee</th>
                            <th>T-Shirt Cost</th>
                            <th>Cost of Timing Chip and Timing Certificate</th>
                        </tr>
                        <tr>
                            <td>3km</td>
                            <td>Bib, Finisher Certificate, Medal</td>
                            <td>300/-</td>
                            <td>200/-</td>
                            <td>150/-</td>
                        </tr>
                        <tr>
                            <td>5km</td>
                            <td>Bib, Finisher Certificate, Medal</td>
                            <td>450/-</td>
                            <td>200/-</td>
                            <td>150/-</td>
                        </tr>
                        <tr>
                            <td>10km</td>
                            <td>Bib, Finisher Certificate, Medal</td>
                            <td>750/-</td>
                            <td>T-shirt is included</td>
                            <td>150/-</td>
                        </tr>
                    </table>
                    <br />
                    <hr>
                    <h4><a id="#terms_hover" href="https://click2race.blob.core.windows.net:443/docs/Terms&Condn_Rules&Regulations_RFH10KRun2016.docx" target="_blank">Terms & Conditions</a></h4>
                    <br/>
                    <div style="text-align: center;font-size: large">
                        <span id="enroll_link"><a href=@Url.Action("FastLane", "Register", new RouteValueDictionary() { { "eventid", "rfh_2016" } }) role="button">Continue</a></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        #enroll_link a:hover {
            color: orangered;
        }
    </style>
    <style>
        #terms_hover a:hover {
            color: orangered;
        }
    </style>
</div>